# Generated by Django 5.1.5 on 2025-01-26 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_card',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ece5489f-5325-4905-92b2-689c126ceed4'), editable=False, primary_key=True, serialize=False, verbose_name='Uniq ID')),
                ('name', models.CharField(max_length=225, verbose_name='name of product')),
                ('description', models.CharField(blank=True, max_length=1134, null=True, verbose_name='Description of product')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link to the product page')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price of the product')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='currency of price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='picture of product')),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('deleted', 'Deleted')], default='active', max_length=10, verbose_name='status of product')),
            ],
            options={
                'verbose_name': "Product's card",
                'verbose_name_plural': "Product's card's",
            },
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
