# Generated by Django 5.1.5 on 2025-01-26 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_product_card_delete_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cfc70c91-b961-4b43-bf1a-171fba0db177'), editable=False, primary_key=True, serialize=False, verbose_name='Uniq ID'),
        ),
    ]
